site_name: GHM File Docs
site_url: https://sevonj.github.io/ghm_docs/
theme:
  name: material
  icon:
    logo: material/star
  favicon: assets/star.png

  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: black
      accent: purple

    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: black
      accent: purple
  features:
    - navigation.indexes
extra_css:
  - stylesheets/extra.css
#plugins:   # Temporarily disabled as this fails on GH actions
#  - privacy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
